#!/bin/bash

echo "🚀 Setup Railway Environment Variables for Separate Databases"
echo "============================================================"
echo ""
echo "1. Go to your Railway project dashboard"
echo "2. Navigate to Variables section"
echo "3. Add these environment variables:"
echo ""
echo "# Database URLs (replace with your actual database URLs)"
echo "DATABASE_URL_USERS=postgresql://postgres:password@containers-us-west-1.railway.app:1234/railway"
echo "DATABASE_URL_KAPAL=postgresql://postgres:password@containers-us-west-2.railway.app:5678/railway"
echo "DATABASE_URL_DOKUMEN=postgresql://postgres:password@containers-us-west-3.railway.app:9012/railway"
echo "DATABASE_URL_KAPAL_MASUK=postgresql://postgres:password@containers-us-west-4.railway.app:3456/railway"
echo ""
echo "# JWT Secret (generate a secure random string)"
echo "JWT_SECRET=your-super-secure-jwt-key-change-this-in-production-make-it-long-and-random"
echo ""
echo "4. After setting variables, redeploy your application"
echo "5. Check logs to ensure all databases connect successfully"
echo ""
echo "📋 Checklist:"
echo "- [ ] DATABASE_URL_USERS set"
echo "- [ ] DATABASE_URL_KAPAL set"
echo "- [ ] DATABASE_URL_DOKUMEN set"
echo "- [ ] DATABASE_URL_KAPAL_MASUK set"
echo "- [ ] JWT_SECRET set"
echo "- [ ] Application redeployed"
echo "- [ ] Logs checked for connection success"
