#!/bin/bash

echo "🚀 Setup Railway Environment Variables for Schema-based Database"
echo "================================================================"
echo ""
echo "1. Go to your Railway project dashboard"
echo "2. Navigate to Variables section"
echo "3. Add these environment variables:"
echo ""
echo "# Single Database URL (Railway provides this automatically)"
echo "DATABASE_URL=postgresql://postgres:password@containers-us-west-1.railway.app:1234/railway"
echo ""
echo "# JWT Secret (generate a secure random string)"
echo "JWT_SECRET=your-super-secure-jwt-key-change-this-in-production-make-it-long-and-random"
echo ""
echo "4. After setting variables, redeploy your application"
echo "5. Check logs to ensure database connects and schemas are created"
echo ""
echo "📋 Checklist:"
echo "- [ ] DATABASE_URL set (Railway provides this)"
echo "- [ ] JWT_SECRET set"
echo "- [ ] Application redeployed"
echo "- [ ] Logs checked for schema creation and connection success"
echo ""
echo "Note: The application will automatically create the following schemas:"
echo "- users_schema (for user management)"
echo "- kapal_schema (for ship information and status)"
echo "- dokumen_schema (for documents)"
echo "- kapal_masuk_schema (for ship entries)"
